use anyhow::{Context, Result};
use colored::Colorize;
use std::fs;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;

const HOOK_SCRIPT: &str = r#"#!/bin/sh
# veil-rs pre-commit hook
# Generated by `veil pre-commit init`

# Run veil scan only on staged files
# If secrets are found, veil will exit with non-zero code
veil scan --staged

SIMPLE_EXIT_CODE=$?

if [ $SIMPLE_EXIT_CODE -ne 0 ]; then
    echo ""
    echo "❌  Commit blocked by Veil Security Check."
    echo "    Secrets were detected in your staged files."
    echo ""
    echo "    To bypass (DANGEROUS): git commit --no-verify"
    echo ""
    exit 1
fi

exit 0
"#;

pub fn init() -> Result<()> {
    let git_dir = Path::new(".git");
    if !git_dir.exists() {
        return Err(anyhow::anyhow!(
            "Current directory is not a git repository. Please run `git init` first."
        ));
    }

    let hooks_dir = git_dir.join("hooks");
    if !hooks_dir.exists() {
        fs::create_dir_all(&hooks_dir).context("Failed to create hooks directory")?;
    }

    let hook_path = hooks_dir.join("pre-commit");
    if hook_path.exists() {
        let backup_path = hooks_dir.join("pre-commit.veil.bak");
        if backup_path.exists() {
            return Err(anyhow::anyhow!(
                "Backup file {:?} already exists. Please move or delete it before running init.",
                backup_path
            ));
        }

        fs::rename(&hook_path, &backup_path)
            .context("Failed to backup existing pre-commit hook")?;
        println!(
            "{} Backed up existing hook to {:?}",
            "ℹ️".blue(),
            backup_path
        );
    }

    fs::write(&hook_path, HOOK_SCRIPT).context("Failed to write pre-commit hook")?;

    #[cfg(unix)]
    {
        let mut perms = fs::metadata(&hook_path)?.permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&hook_path, perms)
            .context("Failed to set executable permissions on hook")?;
    }

    println!(
        "{} Veil pre-commit hook installed successfully!",
        "✅".green()
    );
    println!("   The hook is located at: {:?}", hook_path);

    Ok(())
}
