// Code generated by S12-07 patch script (deterministic, minimal).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func s12_07_scan_docs_pr(root string) int {
stop := 0

prDir := filepath.Join(root, "docs", "pr")
entries, err := os.ReadDir(prDir)
if err != nil {
// docs/pr が無いなら、このフェーズでは強制しない（最小コスト）
fmt.Printf("SKIP: s12-07: docs/pr missing: %s
", prDir)
return 0
}

// “実PR doc” のみ強制（digits必須）
reOK := regexp.MustCompile(`^PR-[0-9]+-.+\.md$`)
tokens := []string{"PR-TBD", "PR-XXX", "PR-??"}

checkContent := func(rel string) {
base := filepath.Base(rel)
if !reOK.MatchString(base) {
// STATUSが参照してるのにPR番号が無い＝事故
fmt.Printf("ERROR: s12-07: STATUS evidence invalid docs/pr filename=%s
", rel)
stop = 1
return
}
b, err := os.ReadFile(filepath.Join(root, rel))
if err != nil {
fmt.Printf("ERROR: s12-07: docs/pr read failed path=%s
", rel)
stop = 1
return
}
txt := string(b)
for _, tok := range tokens {
if strings.Contains(txt, tok) {
fmt.Printf("ERROR: s12-07: docs/pr placeholder token in content path=%s
", rel)
stop = 1
return
}
}
}

// 1) STATUS.md が参照する docs/pr は “実在 + 数値PR + placeholder無し” を強制
status := filepath.Join(root, "docs", "ops", "STATUS.md")
b, err := os.ReadFile(status)
if err == nil {
rePath := regexp.MustCompile(`docs/pr/[A-Za-z0-9._\-\/]+\.md`)
mm := rePath.FindAllString(string(b), -1)
seen := map[string]bool{}
for _, rel := range mm {
if seen[rel] {
continue
}
seen[rel] = true
if _, err := os.Stat(filepath.Join(root, rel)); err != nil {
fmt.Printf("ERROR: s12-07: STATUS evidence missing path=%s
", rel)
stop = 1
continue
}
checkContent(rel)
}
} else {
fmt.Printf("SKIP: s12-07: STATUS.md missing: %s
", status)
}

// 2) docs/pr に存在する “数値PR doc” は placeholder無しを強制
for _, e := range entries {
if e.IsDir() {
continue
}
name := e.Name()
if !reOK.MatchString(name) {
continue // README / template / epic PR-TBD などは Non-Goal として不干渉
}
rel := filepath.Join("docs", "pr", name)
checkContent(rel)
}

if stop == 0 {
fmt.Printf("OK: s12-07: docs/pr naming + STATUS evidence ok
")
}
return stop
}


func s12_07_scan_stdout_audit(root string) int {
	stop := 0

	scripts := filepath.Join(root, "scripts")
	entries, err := os.ReadDir(scripts)
	if err != nil {
		fmt.Printf("SKIP: s12-07: scripts dir missing: %s\n", scripts)
		return 0
	}

	for _, e := range entries {
		if e.IsDir() {
			continue
		}
		name := e.Name()
		if !strings.HasSuffix(name, ".py") {
			continue
		}
		p := filepath.Join(scripts, name)
		b, err := os.ReadFile(p)
		if err != nil {
			fmt.Printf("ERROR: s12-07: scripts read failed path=%s\n", filepath.Join("scripts", name))
			stop = 1
			continue
		}
		s := string(b)
		if strings.Contains(s, "if __name__ == \"__main__\":") || strings.Contains(s, "if __name__ == '__main__':") {
			if !strings.Contains(s, "OK: phase=end") {
				fmt.Printf("ERROR: s12-07: python entrypoint missing OK: phase=end path=%s\n", filepath.Join("scripts", name))
				stop = 1
				continue

			}
		}
	}

	if stop == 0 {
		fmt.Printf("OK: s12-07: python stdout audit ok\n")
	}
	return stop
}

func s12_07_run_all(root string) int {
	stop := 0
	if s12_07_scan_docs_pr(root) != 0 {
		stop = 1
	}
	if s12_07_scan_stdout_audit(root) != 0 {
		stop = 1
	}
	return stop
}

func s12_07_guard_docs_pr(_ string) bool {
	stop := s12_07_scan_docs_pr(".")
	return stop == 0
}

func s12_07_guard_stdout_audit(_ string) bool {
	stop := s12_07_scan_stdout_audit(".")
	return stop == 0
}
